logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: #
            client-secret: #
  data:
    mongodb:
      uri: #
  jpa:
    show-sql: true

